export const SET_EVENT_ANNOUNCES_LIST = "SET_EVENT_ANNOUNCES_LIST";
export const SET_EVENT_ANNOUNCES_LOADING = "SET_EVENT_ANNOUNCES_LOADING";
export const SET_EVENT_ANNOUNCES_ERROR = "SET_EVENT_ANNOUNCES_ERROR";
