export const SET_LESSON_ANNOUNCES_LIST = "SET_LESSON_ANNOUNCES_LIST";
export const SET_LESSON_ANNOUNCES_LOADING = "SET_LESSON_ANNOUNCES_LOADING";
export const SET_LESSON_ANNOUNCES_ERROR = "SET_LESSON_ANNOUNCES_ERROR";
