export const SET_TICKETS_LIST = "SET_TICKETS_LIST";
export const SET_POINTS = "SET_POINTS";
export const SET_TICKETS_LOADING = "SET_TICKETS_LOADING";
export const SET_TICKETS_ERROR = "SET_TICKETS_ERROR";
